#ifndef CALCHOOKPROCESS_GLOBAL_H
#define CALCHOOKPROCESS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CALCHOOKPROCESS_LIBRARY)
#  define CALCHOOKPROCESSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CALCHOOKPROCESSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CALCHOOKPROCESS_GLOBAL_H
